Neos:
  Neos:
    modules:
      administration:
        submodules:
          dynamicRoles:
            label: 'Sandstorm.NeosAcl:Main:module.label'
            controller: 'Sandstorm\NeosAcl\Controller\Module\DynamicRoleController'
            description: 'Sandstorm.NeosAcl:Main:module.description'
            icon: fas fa-user-lock
            mainStylesheet: 'Lite'
            additionalResources:
              javaScripts:
                'Module': 'resource://Sandstorm.NeosAcl/Public/Scripts/Module.js'
              styleSheets:
                'Module': 'resource://Sandstorm.NeosAcl/Public/Styles/Module.css'

    userInterface:
      translation:
        autoInclude:
          Sandstorm.NeosAcl:
            - Main

  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Sandstorm.NeosAcl:Controllers':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Sandstorm\NeosAcl\Controller\.*'

    mvc:
      routes:
        'Sandstorm.NeosAcl':
          position: 'before Neos.Neos'
